Repository modern-agile-team/Menbosha-front, pull requests merged in 2023-12, with the labels that each got.

#33 Oauth 소셜 로그인 구현
  package-lock.json
  src/apis/faker.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/molecules/auth-elements/AuthProvider.tsx
  src/components/organisms/auth/LoginModal.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/hooks/usePreviousUrl.tsx
  src/pages/auth/google/callback/index.tsx
  src/recoil/atoms/test.tsx
Labels: ✨ Feature, 📬 API

#34 로그인 모달 퍼블리싱
  public/Group-88.jpeg
  public/Group-89.jpeg
  public/Group-90.jpeg
  src/components/molecules/auth-elements/AuthProvider.tsx
  src/components/organisms/auth/LoginModal.tsx
Labels: 🎨 Publish

#35 Mentor페이지 퍼블리싱
  src/components/molecules/mentor-board-elements/MentorCard.tsx
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/organisms/help-board/HelpCategory.tsx
  src/components/organisms/mentor-board/styled.ts
  src/components/templates/CreateHelpTemplate.tsx
  src/components/templates/CreateMentorTemplate.tsx
  src/components/templates/HelpTemplate.tsx
  src/components/templates/MentorTemplate.tsx
  src/pages/help/create/index.tsx
  src/pages/help/index.tsx
  src/pages/mentee/index.tsx
  src/pages/mentor/create/index.tsx
Labels: 🎨 Publish

#37 도와주세요 게시글 관련 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/apis/help.ts
  src/apis/search.ts
  src/components/common/category/Category.tsx
  src/components/common/category/CategorySelector.tsx
  src/components/common/category/categoryList.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/molecules/create-board-elements/ChoiceSection.tsx
  src/components/organisms/create-help-board/CreateHelpBody.tsx
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-board/HelpSideViewer.tsx
  src/components/organisms/help-board/styled.ts
  src/components/templates/CreateHelpTemplate.tsx
  src/components/templates/HelpTemplate.tsx
  src/components/templates/MentorTemplate.tsx
  src/pages/_app.tsx
  src/recoil/atoms/CategorySelectAtom.ts
Labels: ✨ Feature, 📬 API

#42 구글 로그인관련 버그수정
  src/apis/oauth.ts
  src/components/molecules/auth-elements/AuthProvider.tsx
  src/components/molecules/create-board-elements/CategorySelector.tsx
  src/components/molecules/create-board-elements/ChoiceSection.tsx
  src/components/molecules/help-board-elements/HelpCard.tsx
  src/components/molecules/help-board-elements/styled.ts
  src/components/organisms/create-help-board/CreateHelpBody.tsx
  src/components/organisms/create-help-board/styled.ts
Labels: 🐞 BugFix

#43 게시글 생성 페이지 퍼블리싱
  src/components/molecules/create-board-elements/CategorySelector.tsx
  src/components/molecules/create-board-elements/ChoiceSection.tsx
  src/components/organisms/create-help-board/CreateHelpBody.tsx
  src/components/organisms/create-help-board/styled.ts
  src/styles/globals.css
Labels: 🎨 Publish

#44 게시글 생성 페이지 드롭다운 UI추가
  src/apis/help.ts
  src/components/organisms/create-help-board/CreateHelpBody.tsx
  src/components/organisms/create-help-board/styled.ts
  src/styles/globals.css
Labels: 🎨 Publish

#45 ChatSpace Publishing
  public/ChatEmoticon.svg
  public/ChatPlusIcon.svg
  public/ChatRoomInfo.svg
  public/ChatRoomOut.svg
  public/ChattingIcon.svg
  src/components/molecules/chat-list-area/chat-list-box/styled.ts
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-body/styled.ts
  src/components/molecules/chat-space-elements/chat-space-footer/ChatSpaceFooter.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/styled.ts
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/chat-space-elements/chat-space-header/styled.ts
  src/components/molecules/chat-space-elements/time-stamp/TimeStamp.tsx
  src/components/molecules/chat-space-elements/time-stamp/styled.ts
  src/components/organisms/chat/chat-list/ChatSearchList.tsx
  src/components/organisms/chat/chat-list/styled.ts
  src/components/organisms/chat/chat-navbar/styled.ts
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/components/organisms/chat/chat-space/styled.ts
  src/components/templates/ChatPageTemplate.tsx
  src/hooks/useReplace.tsx
  src/recoil/selectors/MentorInfoSelector.ts
Labels: 🎨 Publish

#47 도와주세요 게시글 구현(중)
  src/apis/help.ts
  src/components/molecules/help-board-elements/HelpCard.tsx
  src/components/molecules/help-board-elements/styled.ts
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/help-unit/styled.ts
  src/components/templates/HelpUnitTemplate.tsx
  src/pages/auth/naver/callback/index.tsx
  src/pages/help/unit/index.tsx
  src/types/help.d.ts
Labels: ✨ Feature, 📬 API, 🐞 BugFix

#48 도와주세요 게시글 퍼블리싱 진행중
  next.config.js
  src/apis/help.ts
  src/components/common/globalStyled/styled.ts
  src/components/molecules/help-board-elements/HelpCard.tsx
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/molecules/help-unit-elements/UnitContentBody.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/help-unit/styled.ts
  src/components/templates/HelpUnitTemplate.tsx
  src/hooks/usePreviousUrl.tsx
  src/pages/help/unit/[id].tsx
  src/types/help.d.ts
Labels: 🎨 Publish
