Repository modern-agile-team/Menbosha-front, pull requests merged in 2024-03, with the labels that each got.

#179 프로필 수정 페이지 수정
  src/components/common/category/Category.tsx
  src/components/organisms/my-profile/UpdateMyProfile.tsx
  src/components/organisms/my-profile/styled.tsx
Labels: 📝 Modify

#181 deploy(#152) docker-compose를 통한 restart
  .github/workflows/ma6-menbosha.yml
Labels: 🌏 Deploy

#182 deploy(#152) action main으로 변경
  .github/workflows/ma6-menbosha.yml
Labels: 🌏 Deploy

#185 폰트 적용
  src/components/common/category/styled.ts
  src/components/common/footer/styled.tsx
  src/components/common/globalStyled/styled.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/molecules/help-board-elements/styled.ts
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/molecules/mainpagebody-contents/BodyContents2.tsx
  src/components/molecules/mainpagebody-contents/BodyContents3.tsx
  src/components/molecules/mainpagebody-contents/BodyContents4.tsx
  src/components/molecules/mainpagebody-contents/styled.tsx
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-board-elements/MentorOtherBoardCard.tsx
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBody.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
  src/components/molecules/mentor-elements/PopularMentorCard.tsx
  src/components/molecules/mentor-elements/styled.tsx
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/molecules/mentor-review-elements/styled.tsx
  src/components/molecules/my-page-elements/styled.tsx
  src/components/organisms/mainpage-body/marquee/CategoryMarquee.tsx
  src/components/organisms/mainpage-body/marquee/styled.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/styled.ts
  src/components/organisms/my-profile/UpdateMyProfile.tsx
  src/components/organisms/my-profile/styled.tsx
  src/components/organisms/my-record/MyRecordContents.tsx
  src/components/organisms/my-record/styled.tsx
  src/components/organisms/my-review/MyReviewContents.tsx
  src/components/organisms/my-review/styled.tsx
  src/components/organisms/support-combo-box/styled.ts
  src/components/templates/help-template/HelpTemplate.tsx
  src/components/templates/help-template/styled.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/components/templates/mypage-template/BadgeTemplate.tsx
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/MyProfileTemplate.tsx
  src/components/templates/mypage-template/MyRecordTemplate.tsx
  src/components/templates/mypage-template/MyReviewTemplate.tsx
  src/components/templates/mypage-template/UpdateMyProfileTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/components/templates/support-template/QnATemplate.tsx
  src/components/templates/support-template/styled.tsx
  src/pages/_app.tsx
  src/pages/help/index.tsx
  src/pages/mentor/board/index.tsx
  src/pages/mentor/index.tsx
  src/styles/globals.css
Labels: 🎨 Publish

#188 feature(#187):404페이지생성
  src/pages/404.tsx
Labels: ✨ Feature

#191 deploy(#152) 탄력적 ip 적용
  nginx.conf
Labels: 🌏 Deploy

#190 Feat/my review 1/#183
  src/apis/mentors.ts
  src/components/common/check-list/checkList.ts
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/my-review/MyReviewContents.tsx
  src/components/organisms/my-review/styled.tsx
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/styled.ts
Labels: ✨ Feature, 🎨 Publish

#194 릴리즈 전 수정사항들
  src/components/molecules/my-page-elements/MyBadge.tsx
  src/components/molecules/my-page-elements/styled.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/my-profile/styled.tsx
  src/components/organisms/my-review/styled.tsx
  src/components/organisms/reivew-element/CreateReview.tsx
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/types/user.d.ts
Labels: 📝 Modify

#195 로그인 리다이렉트 확인용 pr
  src/components/molecules/my-page-elements/MyBadge.tsx
  src/components/molecules/my-page-elements/styled.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/my-profile/styled.tsx
  src/components/organisms/my-review/styled.tsx
  src/components/organisms/reivew-element/CreateReview.tsx
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/types/user.d.ts
Labels: 🐞 BugFix

#196 nextconfig수정
  next.config.js
  src/components/organisms/auth/SaveToken.tsx
Labels: 🐞 BugFix

#197 www nextconfig수정
  next.config.js
Labels: 🐞 BugFix

#198 Feat/chatting 2/#114 - Fix
  src/components/common/footer/styled.tsx
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/mainpagebody-contents/styled.tsx
  src/components/organisms/chat/chat-navbar/ChatNavbar.tsx
  src/components/organisms/chat/chat-navbar/styled.ts
  src/components/organisms/mainpage-body/marquee/styled.tsx
  src/components/organisms/mainpage-body/styled.tsx
  src/components/organisms/review-element/CreateReview.tsx
  src/components/organisms/review-element/styled.tsx
  src/components/organisms/review/ReviewModal.tsx
  src/hooks/useSocket.tsx
Labels: 🎨 Publish, 📝 Modify

#200 배포전 이슈 수정
  next.config.js
  src/apis/helpComment.ts
  src/apis/user.ts
  src/components/common/Seo.tsx
  src/components/common/badge-list/badge.ts
  src/components/common/header/styled.ts
  src/components/molecules/create-board-elements/CategorySelector.tsx
  src/components/molecules/create-board-elements/ChoiceSection.tsx
  src/components/molecules/help-board-elements/styled.ts
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/molecules/mentor-elements/MentorBadgeElements.tsx
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/molecules/mentor-review-elements/styled.tsx
  src/components/molecules/my-page-elements/BadgeNotification.tsx
  src/components/molecules/my-page-elements/MyBadge.tsx
  src/components/molecules/my-page-elements/styled.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/organisms/create-board/CreateBody.tsx
  src/components/organisms/create-board/styled.ts
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/styled.ts
  src/components/organisms/my-badge/MyBadgeContents.tsx
  src/components/organisms/my-profile/MyProfileConetents.tsx
  src/components/organisms/my-profile/UpdateMyProfile.tsx
  src/components/organisms/my-review/styled.tsx
  src/components/organisms/support-withdrawal/UserWithdrawal.tsx
  src/components/templates/mypage-template/styled.ts
  src/recoil/atoms/NotificationAtom.ts
  src/types/mypage.d.ts
  src/types/user.d.ts
Labels: 📝 Modify

#204 리다이렉트 수정사항
  next.config.js
  src/apis/axiosInstance.ts
  src/apis/oauth.ts
  src/components/organisms/auth/LoginModal.tsx
  src/components/organisms/auth/SaveToken.tsx
Labels: 📝 Modify

#205 Bugfix/chatting fix/#199 - 채팅 예외처리
  src/apis/chat.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomOutModal.tsx
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-body/styled.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/ChatSpaceFooter.tsx
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/components/templates/ChatPageTemplate.tsx
Labels: 🐞 BugFix

#206 네이버 서치 메타태그 추가
  next.config.js
  src/apis/axiosInstance.ts
  src/components/common/Seo.tsx
  src/components/common/globalStyled/styled.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/organisms/auth/AfterLoginModal.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/organisms/chat/chat-navbar/ChatNavbar.tsx
  src/components/organisms/support-withdrawal/UserWithdrawal.tsx
  src/components/templates/CreateTemplate.tsx
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/pages/index.tsx
Labels: ✨ Feature

#208 Bugfix/chatting fix/#199 - consoln.log 삭제 및 미사용 컴포넌트 삭제
  src/apis/chat.ts
  src/components/common/footer/Footer.tsx
  src/components/common/footer/styled.tsx
  src/components/common/header/styled.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomOutModal.tsx
  src/components/molecules/chat-list-area/chat-list-box/styled.ts
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/components/molecules/chat-space-elements/chat-space-body/ChatDeleteModal.tsx
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-body/styled.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/ChatSpaceFooter.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/styled.ts
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/chat-space-elements/chat-space-header/styled.ts
  src/components/organisms/chat/chat-list/ChatMentorList.tsx
  src/components/organisms/chat/chat-list/ChatRoomList.tsx
  src/components/organisms/chat/chat-navbar/ChatNavbar.tsx
  src/components/organisms/chat/chat-navbar/styled.ts
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/components/organisms/mainpage-body/Carousel.tsx
  src/components/organisms/mainpage-body/MainPageBody.tsx
  src/components/organisms/mainpage-body/styled.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/components/templates/styled.tsx
  src/recoil/atoms/ChatPartnersAtom.ts
  src/types/chat.d.ts
Labels: 🐞 BugFix

#210 Bugfix/chatting fix/#199
  src/components/templates/ChatPageTemplate.tsx
Labels: 🐞 BugFix

#209 console.log 및 미사용 컴포넌트 삭제
  src/components/common/footer/Footer.tsx
  src/components/common/footer/styled.tsx
  src/components/common/header/styled.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomOutModal.tsx
  src/components/molecules/chat-list-area/chat-list-box/styled.ts
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/components/molecules/chat-space-elements/chat-space-body/ChatDeleteModal.tsx
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/ChatSpaceFooter.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/styled.ts
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/chat-space-elements/chat-space-header/styled.ts
  src/components/organisms/chat/chat-list/ChatMentorList.tsx
  src/components/organisms/chat/chat-list/ChatRoomList.tsx
  src/components/organisms/chat/chat-navbar/ChatNavbar.tsx
  src/components/organisms/chat/chat-navbar/styled.ts
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/components/organisms/mainpage-body/Carousel.tsx
  src/components/organisms/mainpage-body/MainPageBody.tsx
  src/components/organisms/mainpage-body/styled.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/components/templates/styled.tsx
  src/recoil/atoms/ChatPartnersAtom.ts
  src/types/chat.d.ts
Labels: 🐞 BugFix

#211 Bugfix/chatting fix/#199
  src/components/molecules/chat-space-elements/chat-space-footer/ChatSpaceFooter.tsx
  src/components/templates/ChatPageTemplate.tsx
Labels: 🐞 BugFix

#213 회원탈퇴 기능 수정
  src/components/molecules/mentor-elements/styled.tsx
  src/components/organisms/support-withdrawal/UserWithdrawal.tsx
  src/components/organisms/support-withdrawal/styled.ts
Labels: 📝 Modify

#214 리뷰 기능 추가
  src/components/organisms/review-element/CreateReview.tsx
  src/components/organisms/review-element/styled.tsx
  src/components/organisms/review/ReviewModal.tsx
Labels: ✨ Feature

#216 스크롤 업 구현
  src/components/common/scroll-to-top/ScrollToTopButton.tsx
  src/components/common/scroll-to-top/styled.tsx
  src/components/molecules/mainpagebody-contents/BodyContents5.tsx
  src/components/molecules/mainpagebody-contents/styled.tsx
  src/components/organisms/mainpage-body/MainPageBody.tsx
  src/components/templates/MainPageTemplate.tsx
  src/components/templates/styled.tsx
  src/pages/_app.tsx
Labels: ✨ Feature

#220 vercel cors허용
  next.config.js
  src/apis/axiosInstance.ts
Labels: 💻 CrossBrowsing

#221 vercel 개발 서버 배포
  next.config.js
  src/components/common/Seo.tsx
Labels: 💻 CrossBrowsing

#222 cross(#219):rewites하기
  next.config.js
Labels: 💻 CrossBrowsing

#223 vercel api요청 rewrites
  next.config.js
Labels: 💻 CrossBrowsing

#224 cross(#219):vercel 실패...우선 주석처리..나중에 사용하면 사용
  next.config.js
Labels: 💻 CrossBrowsing

#225 publish(#218):마이페이지 트렌지션 적용
  src/components/molecules/my-page-elements/MyBadge.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/mentor/styled.ts
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/styled.ts
Labels: 🎨 Publish

#226 publish(#218):추가 못한 사항 추가
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/styled.ts
Labels: 🎨 Publish

#227 Bugfix/front bug fix/#202
  next.config.js
  src/apis/help.ts
  src/apis/mentor.ts
  src/apis/user.ts
  src/components/common/Seo.tsx
  src/components/molecules/my-page-elements/MyRank.tsx
  src/components/molecules/my-page-elements/styled.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/organisms/modify-help-board/ModifyHelpBoard.tsx
  src/components/organisms/my-badge/MyBadgeContents.tsx
  src/types/mypage.d.ts
Labels: 🐞 BugFix

#228 redirect를 위한 middleware등록
  next.config.js
  src/apis/axiosInstance.ts
  src/components/common/footer/Footer.tsx
  src/components/common/footer/styled.tsx
  src/components/common/header/MainPageHeader.tsx
  src/components/organisms/auth/AfterLoginModal.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/organisms/support-withdrawal/UserWithdrawal.tsx
  src/middleware.ts
  src/recoil/atoms/LoginStateAtom.ts
Labels: 🐞 BugFix

#229 fix(#199): 에러핸들링 - 배포 전 마무리
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/components/molecules/chat-space-elements/chat-space-body/styled.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/ChatSpaceFooter.tsx
  src/components/molecules/chat-space-elements/chat-space-footer/styled.ts
  src/components/molecules/chat-space-elements/chat-space-header/ChatInfoModal.tsx
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/mainpagebody-contents/styled.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/review/ReviewModal.tsx
Labels: 📝 Modify

#230 멘토 유닛 이미지 비율 수정
  src/components/common/header/MainPageHeader.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
Labels: 🐞 BugFix

#233 bugfix(#232):redirect수정
  src/components/organisms/auth/SaveToken.tsx
Labels: 🐞 BugFix

#234 fix(#199): 퍼블리싱 수정
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
Labels: 🎨 Publish

#237 Bugfix/chatting fix/#199 - 채팅 시작 시 로그인
  src/components/common/header/MainPageHeader.tsx
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/templates/ChatPageTemplate.tsx
Labels: 📝 Modify

#238 fix(#199): 수정
  src/components/templates/ChatPageTemplate.tsx
Labels: 🐞 BugFix

#236 멘토리스트 비율 수정
  src/components/molecules/mentor-elements/styled.tsx
Labels: 🐞 BugFix

#239 fix(#199): 마지막 수정
  src/components/common/header/MainPageHeader.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/components/templates/MainPageTemplate.tsx
Labels: 📝 Modify

#240 배포 전 문구 정리
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-body/styled.tsx
Labels: 📝 Modify

#247 모달창 스크롤 막기
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/molecules/side-bar-elements/SideBarReactive.tsx
  src/components/molecules/side-bar-elements/styled.tsx
  src/components/organisms/auth/LoginModal.tsx
Labels: 📝 Modify

#253 서브도메인 리다이렉트 수정
  next.config.js
  package.json
  src/middleware.ts
Labels: 📝 Modify

#254 수정사항 수정
  src/apis/axiosInstance.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBody.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBottom.tsx
  src/components/molecules/mentor-elements/PopularMentorCard.tsx
  src/components/molecules/mentor-elements/styled.tsx
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/RankMentor.tsx
  src/components/organisms/mentor/styled.ts
  src/components/templates/help-template/HelpTemplate.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
Labels: 📝 Modify

#258 스켈레톤 UI수정, 멘토 게시글 렌더링 버그 수정
  src/components/common/skeletonUI/SkeletonUI.tsx
  src/components/molecules/help-unit-elements/HelpUnitContentBodySkeleton.tsx
  src/components/molecules/help-unit-elements/HelpUnitContentHeadSkeleton.tsx
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBodySkeleton.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHeadSkeleton.tsx
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-board/HelpPullingBoardList.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor-board/RandomMentorBoard.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/RankMentor.tsx
Labels: 🐞 BugFix

#257 토큰에러수정
  src/apis/axiosInstance.ts
  src/components/common/header/MainPageHeader.tsx
Labels: 📝 Modify

#259 마이페이지 기록 페이지 수정
  src/apis/help.ts
  src/apis/mentor.ts
Labels: 📝 Modify

#260 리스트 페이지 수정 및 추가
  src/components/common/globalStyled/styled.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/molecules/mentor-elements/styled.tsx
  src/components/molecules/side-bar-elements/SideBarReactive.tsx
  src/components/templates/help-template/HelpTemplate.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/support-template/SupportTemplate.tsx
Labels: ✨ Feature, 📝 Modify

#263 사이트 프리뷰 생성
  src/components/common/Seo.tsx
Labels: ✨ Feature

#241 Bugfix/chatting fix/#199 - chatting Alarm(Merge NONO)
  README.md
  src/components/common/footer/styled.tsx
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/molecules/mainpagebody-contents/styled.tsx
  src/components/organisms/mainpage-body/marquee/styled.tsx
  src/components/templates/MainPageTemplate.tsx
  src/recoil/atoms/UserIdAtom.ts
Labels: 🎨 Publish, 📝 Modify

#262 토큰에러 수정
  src/apis/axiosInstance.ts
Labels: 📝 Modify
