Repository modern-agile-team/Menbosha-front, pull requests merged in 2024-04, with the labels that each got.

#266 폰트 적용방식 변경
  src/components/common/globalStyled/styled.ts
  src/pages/_app.tsx
  src/styles/globals.css
Labels: 🎨 Publish

#267 폰트 적용방식 변경2
  src/components/common/Seo.tsx
  src/pages/_app.tsx
  src/pages/fonts/Pretendard-Black.woff2
  src/pages/fonts/Pretendard-Bold.woff2
  src/pages/fonts/Pretendard-ExtraBold.woff2
  src/pages/fonts/Pretendard-ExtraLight.woff2
  src/pages/fonts/Pretendard-Light.woff2
  src/pages/fonts/Pretendard-Medium.woff2
  src/pages/fonts/Pretendard-Regular.woff2
  src/pages/fonts/Pretendard-SemiBold.woff2
  src/pages/fonts/Pretendard-Thin.woff2
  src/styles/globals.css
Labels: 🎨 Publish

#269 fix(#246): 긴급 수정
  src/components/common/globalStyled/styled.ts
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
Labels: 📝 Modify

#270 readme.md 영상 제작 전 긴급수정
  src/components/common/globalStyled/styled.ts
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
Labels: 🐞 BugFix

#271 fix(#246): 긴급 수정2
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/organisms/create-board/CreateBody.tsx
  src/components/organisms/create-board/styled.ts
  src/components/organisms/my-profile/MyProfileConetents.tsx
Labels: 🐞 BugFix

#272 영상제작 전 마지막 수정
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/organisms/create-board/CreateBody.tsx
  src/components/organisms/create-board/styled.ts
  src/components/organisms/my-profile/MyProfileConetents.tsx
Labels: 🐞 BugFix
