Repository modern-agile-team/Menbosha-front, pull requests merged in 2024-01, with the labels that each got.

#50 페이지 route 스크롤 기능 구현
  src/apis/help.ts
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/pages/_document.tsx
Labels: 📝 Modify

#51 chatRoomList api 선언부 설계
  src/apis/chatApi/chat.ts
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/organisms/mainpage-body/Carousel.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/recoil/atoms/ChatRoomListAtom.ts
  src/recoil/atoms/MentorInfoAtom.ts
  src/types/chat.d.ts
Labels: 📬 API

#52 도와주세요, 삭제 수정 기능 추가
  src/apis/help.ts
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/modify-help-board/ModifyHelpBoard.tsx
  src/components/organisms/modify-help-board/styled.ts
  src/components/templates/ModifyHelpTemplate.tsx
  src/pages/help/modify/index.tsx
  src/types/help.d.ts
Labels: ✨ Feature, 📬 API

#54 로그아웃 기능 추가
  public/LogoIcon.svg
  public/LogoText.svg
  public/MenboshaLogo.png
  public/MenboshaLogo2.png
  src/apis/oauth.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/molecules/auth-elements/AuthProvider.tsx
  src/components/organisms/auth/AfterLoginModal.tsx
  src/components/organisms/auth/LoginModal.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/templates/UserPageTemplate.tsx
Labels: ✨ Feature

#55 도와주세요 게시판 스크롤 복구
  src/components/organisms/help-board/HelpBoardCardList.tsx
Labels: 📝 Modify

#56 새로고침시에도 로드
  src/components/organisms/help-board/HelpBoardCardList.tsx
Labels: 📝 Modify

#57 마이페이지 퍼블리싱
  public/chatLInkIcon.png
  public/profileLinkIcon.png
  public/reviewLinkIcon.png
  public/tempIcon.png
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/templates/ContentsTemplate.tsx
  src/components/templates/SettingTemplate.tsx
  src/components/templates/UserPageTemplate.tsx
  src/components/templates/userpage-template/UserPageTemplate.tsx
  src/components/templates/userpage-template/styled.ts
  src/pages/contents/index.tsx
  src/pages/setting/index.tsx
  src/pages/userpage/badge/index.tsx
  src/pages/userpage/index.tsx
  src/pages/userpage/info/index.tsx
  src/pages/userpage/review/index.tsx
  src/pages/userpage/setting/index.tsx
Labels: 🎨 Publish

#58 엑세스토큰 재발급 로직수정
  src/apis/axiosInstance.ts
Labels: 📝 Modify

#60 멘토구현시작
  src/apis/help.ts
  src/apis/mentor.ts
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/MentorList.tsx
  src/components/organisms/mentor-board/MentorSideViewer.tsx
  src/components/organisms/mentor-board/styled.ts
  src/components/templates/MentorTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/pages/mentor/index.tsx
  src/types/help.d.ts
  src/types/mentor.d.ts
Labels: ✨ Feature

#61 멘토게시판퍼블리싱
  src/apis/mentor.ts
  src/apis/user.ts
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-board-elements/MentorCard.tsx
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/MentorList.tsx
  src/components/organisms/mentor-board/styled.ts
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/types/mentor.d.ts
  src/types/user.d.ts
Labels: 🎨 Publish, 📬 API

#63 멘토 게시글 라우트 변경(파일변경 다수)
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/components/templates/userpage-template/UserPageTemplate.tsx
  src/pages/mypage/badge/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/info/index.tsx
  src/pages/mypage/review/index.tsx
  src/pages/userpage/[id].tsx
  src/pages/userpage/badge/index.tsx
  src/pages/userpage/index.tsx
  src/pages/userpage/info/index.tsx
  src/pages/userpage/review/index.tsx
  src/pages/userpage/setting/index.tsx
  src/types/mentor.d.ts
Labels: 📝 Modify

#65 채팅룸리스트 API 연동
  src/apis/chatApi/chat.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatListBox.tsx
  src/components/organisms/chat/chat-list/ChatRoomList.tsx
  src/components/organisms/chat/chat-navbar/ChatNavbar.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/recoil/atoms/ChatRoomListAtom.ts
  src/types/chat.d.ts
Labels: 📬 API

#69 멘토유닛퍼블리싱(중단)
  next.config.js
  src/apis/mentor.ts
  src/apis/user.ts
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBottom.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHead.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
  src/hooks/useCarousel.tsx
  src/pages/mentor/unit/[id].tsx
  src/types/mentor.d.ts
Labels: ✨ Feature

#70 멘토리스트 API연동 및 무한스크롤 구현
  next.config.js
  src/apis/user.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-space-elements/chat-space-body/styled.ts
  src/components/molecules/chat-space-elements/chat-space-footer/styled.ts
  src/components/molecules/chat-space-elements/chat-space-header/styled.ts
  src/components/templates/ChatPageTemplate.tsx
  src/types/chat.d.ts
Labels: 📬 API

#71 멘토 게시판으로 이동을 위한 헤더 수정
  src/apis/help.ts
  src/apis/mentor.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/molecules/create-board-elements/ChoiceSection.tsx
  src/components/organisms/create-board/CreateBody.tsx
  src/components/organisms/create-board/styled.ts
  src/components/templates/CreateMentorTemplate.tsx
  src/components/templates/CreateTemplate.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/pages/create/index.tsx
  src/pages/help/create/index.tsx
  src/pages/mentor/create/index.tsx
Labels: ✨ Feature, 🎨 Publish

#73 멘토 게시글 삭제 기능 추가
  next.config.js
  src/apis/mentor.ts
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHead.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/types/mentor.d.ts
Labels: ✨ Feature, 📝 Modify

#75 publish(#49):멘토 게시글 반응형 작업
  src/components/common/globalStyled/styled.ts
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBody.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
Labels: 🎨 Publish

#76 refactor(#14) dockerfile
  dockerfile
Labels: 🌏 Deploy

#79 Hotfix (Test용)
  src/apis/chatApi/chat.ts
  src/apis/user.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/hooks/useCreateRoom.tsx
  src/pages/auth/google/callback/index.tsx
  src/pages/auth/kakao/callback/index.tsx
  src/pages/auth/naver/callback/index.tsx
  src/pages/chat/[id].tsx
  src/pages/help/create/index.tsx
  src/pages/help/index.tsx
  src/pages/help/modify/index.tsx
  src/pages/mentor/board/index.tsx
  src/pages/mentor/board/unit/[id].tsx
  src/pages/mentor/create/index.tsx
  src/pages/mypage/badge/index.tsx
  src/pages/mypage/info/index.tsx
  src/types/chat.d.ts
Labels: 🐞 BugFix

#82 sharp 관련 fix
  src/apis/chatApi/chat.ts
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/organisms/auth/AfterLoginModal.tsx
Labels: 🐞 BugFix

#83 배경색에 맞게 디자인 수정
  next.config.js
  src/apis/help.ts
  src/components/common/category/Category.tsx
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/molecules/create-board-elements/CategorySelector.tsx
  src/components/molecules/create-board-elements/ChoiceSection.tsx
  src/components/molecules/help-board-elements/HelpCard.tsx
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHead.tsx
  src/components/organisms/create-board/CreateBody.tsx
  src/components/organisms/create-board/styled.ts
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/organisms/modify-help-board/ModifyHelpBoard.tsx
  src/components/organisms/modify-help-board/styled.ts
  src/components/templates/CreateTemplate.tsx
  src/components/templates/HelpTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/types/help.d.ts
Labels: 🎨 Publish

#85 채팅룸 데이터 구조 변경, 채팅룸 생성 훅
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/components/organisms/chat/chat-list/ChatRoomList.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/hooks/useCreateRoom.tsx
  src/pages/chat/index.tsx
  src/recoil/atoms/ChatRoomListAtom.ts
Labels: ✨ Feature, 📬 API

#87 feat(#86):도와주세요 끌올 기능 추가
  src/apis/help.ts
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-board/HelpPullingBoardList.tsx
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/templates/HelpTemplate.tsx
  src/types/help.d.ts
Labels: ✨ Feature

#89 채팅방 생성 API 완료 및 삭제 모달 퍼블리싱
  public/chat/ChatRoomTab.png
  public/chat/ChatToolTip.png
  src/apis/chatApi/chat.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomOutModal.tsx
  src/components/molecules/chat-list-area/chat-list-box/styled.ts
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/hooks/useCreateRoom.tsx
  src/types/chat.d.ts
Labels: 🎨 Publish, 📬 API

#88 feat(#86):카테고리 리스트 기능추가
  src/apis/help.ts
  src/components/common/category/Category.tsx
  src/components/common/category/categoryList.ts
  src/components/common/category/styled.ts
  src/components/molecules/create-board-elements/CategorySelector.tsx
  src/components/molecules/help-board-elements/HelpCard.tsx
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/recoil/atoms/CategorySelectAtom.ts
  src/recoil/atoms/LoginStateAtom.ts
  src/recoil/atoms/MentorInfoAtom.ts
Labels: ✨ Feature

#91 feat(#90):포인트 카운트 기능 추가
  src/apis/count.ts
  src/apis/mentor.ts
  src/components/molecules/help-board-elements/HelpCard.tsx
Labels: ✨ Feature

#92 feat(#80): 채팅방 삭제 및 타입 값 수정
  src/components/molecules/chat-list-area/chat-list-box/ChatListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomOutModal.tsx
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/types/chat.d.ts
Labels: ✨ Feature, 📬 API

#94 Feat/api test 1/#86
  src/apis/help.ts
  src/apis/mentor.ts
  src/components/common/category/Category.tsx
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/RandomMentorBaord.tsx
  src/components/organisms/mentor-board/styled.ts
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
Labels: ✨ Feature

#95 도와주세요 댓글 api 추가
  src/apis/help.ts
  src/apis/helpComment.ts
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/templates/ModifyHelpTemplate.tsx
  src/types/help.d.ts
Labels: 📬 API

#97 bugFix(#86):dockertest
  src/components/templates/ChatPageTemplate.tsx
Labels: 🌏 Deploy

#100 Bugfix/image file fix/#93
  src/components/common/footer/Footer.tsx
  src/components/common/footer/styled.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/SubPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/styled.ts
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/components/molecules/chat-space-elements/chat-space-footer/ChatSpaceFooter.tsx
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/chat-space-elements/chat-space-header/styled.ts
  src/components/organisms/chat/chat-list/ChatMentorList.tsx
  src/components/organisms/chat/chat-list/styled.ts
  src/components/organisms/chat/chat-navbar/ChatNavbar.tsx
  src/components/organisms/chat/chat-navbar/styled.ts
  src/components/organisms/mainpage-body/Carousel.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/templates/CreateTemplate.tsx
  src/components/templates/HelpTemplate.tsx
  src/components/templates/HelpUnitTemplate.tsx
  src/components/templates/ModifyHelpTemplate.tsx
  src/components/templates/SettingTemplate.tsx
  src/components/templates/SupportTemplate.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorBoardUnitTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/components/templates/userpage-template/UserpageTemplate.tsx
Labels: 🎨 Publish, 📝 Modify

#101 도와줄게요 댓글 추가 삭제 기능 추가
  next.config.js
  src/apis/helpComment.ts
  src/apis/user.ts
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/types/help.d.ts
  src/types/user.d.ts
Labels: ✨ Feature, 🎨 Publish

#103 도와주세요 댓글 카운트 로직 활성화
  src/apis/helpComment.ts
Labels: 📝 Modify

#106 게시글 수정 로직 수정
  next.config.js
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/modify-help-board/ModifyHelpBoard.tsx
  src/components/templates/ModifyHelpTemplate.tsx
  src/types/mentor.d.ts
Labels: 📝 Modify

#107 Feat/chatting 1/#80 - Fix
  src/apis/chatApi/chat.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomOutModal.tsx
  src/components/molecules/chat-space-elements/chat-space-body/styled.ts
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/components/templates/MainTemplate.tsx
  src/recoil/atoms/SelectedRoomIdAtom.ts
  src/types/chat.d.ts
Labels: 📝 Modify

#108 Feat/mentor 1/#49
  src/apis/user.ts
  src/components/common/globalStyled/styled.ts
  src/components/molecules/mentor-board-elements/MentorCard.tsx
  src/components/molecules/mentor-elements/MentorCard.tsx
  src/components/molecules/mentor-elements/PopularMentorCard.tsx
  src/components/molecules/mentor-elements/styled.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/organisms/mentor/PopularMentor.tsx
  src/components/organisms/mentor/styled.ts
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/types/user.d.ts
Labels: 🎨 Publish

#109 feat(#49):멘토 유닛 페이지 구성
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
Labels: ✨ Feature

#110 modfiy(#102):access_token재발급 로직 수정
  src/apis/axiosInstance.ts
Labels: 📝 Modify

#111 feat(#80): chattingBody 연결
  src/components/common/header/MainPageHeader.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/chat-space-elements/chat-space-header/styled.ts
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/recoil/atoms/ChatPartnersAtom.ts
  src/types/chat.d.ts
Labels: ✨ Feature, 📝 Modify

#115 modify(#102):auth수정
  src/apis/axiosInstance.ts
Labels: 📝 Modify

#116 멘토게시판 좋아요 기능 추가
  src/apis/mentor.ts
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBody.tsx
  src/components/molecules/mentor-elements/PopularMentorCard.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor-board/RandomMentorBaord.tsx
  src/types/mentor.d.ts
Labels: ✨ Feature

#117 Feat/chatting 2/#114
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/styled.ts
  src/components/molecules/chat-list-area/mentor-list-box/styled.ts
  src/components/molecules/chat-space-elements/chat-space-body/ChatSpaceBody.tsx
  src/components/molecules/chat-space-elements/chat-space-body/styled.tsx
  src/components/molecules/chat-space-elements/chat-space-header/ChatSpaceHeader.tsx
  src/components/molecules/chat-space-elements/time-stamp/TimeStamp.tsx
  src/components/molecules/chat-space-elements/time-stamp/styled.ts
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/types/chat.d.ts
Labels: ✨ Feature, 📬 API

#118 좋아요 기능 추가
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBody.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBottom.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/types/mentor.d.ts
Labels: ✨ Feature

#119 좋아요 카운트 추가
  src/apis/mentor.ts
Labels: ✨ Feature

#121 Publish/mainPage republish 1/#112
  package-lock.json
  package.json
  src/components/common/header/MainPageHeader.tsx
  src/components/common/header/styled.ts
  src/components/organisms/mainpage-body/Carousel.tsx
  src/components/organisms/mainpage-body/MainPageBody.tsx
  src/components/organisms/mainpage-body/styled.ts
  src/components/organisms/mainpage-body/styled.tsx
  src/components/templates/MainPageTemplate.tsx
  src/components/templates/styled.tsx
  src/pages/main/index.tsx
Labels: 🎨 Publish

#123 유저 정보 조회/수정 구현
  src/apis/count.ts
  src/apis/helpComment.ts
  src/apis/mentor.ts
  src/apis/user.ts
  src/components/organisms/my-profile/MyProfileConetents.tsx
  src/components/organisms/my-profile/UpdateMyProfile.tsx
  src/components/organisms/my-profile/styled.tsx
  src/components/templates/mypage-template/MyProfileTemplate.tsx
  src/components/templates/mypage-template/UpdateMyProfileTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/pages/mypage/info/index.tsx
  src/pages/mypage/info/update/index.tsx
  src/types/user.d.ts
Labels: ✨ Feature
