Repository modern-agile-team/Menbosha-front, pull requests merged in 2024-02, with the labels that each got.

#125 마이페이지 기능추가
  src/apis/axiosInstance.ts
  src/apis/user.ts
  src/components/common/rank/rankList.ts
  src/components/organisms/my-badge/MyBadge.tsx
  src/components/organisms/my-badge/MyRank.tsx
  src/components/organisms/my-badge/styled.tsx
  src/components/templates/mypage-template/BadgeTemplate.tsx
  src/components/templates/mypage-template/MyPageTemplate.tsx
  src/components/templates/mypage-template/MyProfileTemplate.tsx
  src/components/templates/mypage-template/MyRecordTemplate.tsx
  src/components/templates/mypage-template/MyReviewTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/pages/mypage/badge/index.tsx
  src/pages/mypage/record/index.tsx
  src/pages/mypage/review/index.tsx
  src/types/user.d.ts
Labels: ✨ Feature

#127 멘토페이지 리뷰 불러오기 구현
  next.config.js
  src/apis/mentors.ts
  src/components/molecules/mentor-elements/MentorBadgeElements.tsx
  src/components/molecules/mentor-elements/styled.tsx
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/molecules/mentor-review-elements/styled.tsx
  src/components/organisms/mentor/MentorReveiw.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/styled.ts
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/types/mentor.d.ts
  src/types/review.d.ts
  src/types/user.d.ts
Labels: ✨ Feature

#128 멘토 리뷰 불러오기 기능 구현
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/molecules/mentor-review-elements/styled.tsx
  src/components/organisms/mentor/MentorReveiw.tsx
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/types/review.d.ts
Labels: ✨ Feature

#130 Publish/board 2/#120
  src/components/common/category/Category.tsx
  src/components/common/category/styled.ts
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/organisms/mentor-board/styled.ts
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mentor-template/styled.ts
Labels: 🎨 Publish

#131 Refactor/board 3/#129
  src/apis/help.ts
  src/apis/mentor.ts
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-board/HelpPullingBoardList.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor-board/RandomMentorBaord.tsx
  src/types/help.d.ts
  src/types/mentor.d.ts
Labels: 🔨 Refactor

#132 modify(#129):수정
  src/apis/mentor.ts
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
Labels: 🔨 Refactor

#133 refactor(#129):merge수정
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor-board/RandomMentorBaord.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/types/help.d.ts
  src/types/mentor.d.ts
Labels: ✨ Feature, 🔨 Refactor

#134 Refactor/board 3/#129
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
Labels: 📝 Modify

#135 Publish/board 2/#120
  src/apis/help.ts
  src/components/common/globalStyled/styled.ts
  src/components/molecules/help-board-elements/HelpCard.tsx
  src/components/molecules/help-board-elements/styled.ts
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-board/HelpPullingBoardList.tsx
  src/components/organisms/help-board/styled.ts
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/help-unit/styled.ts
  src/components/templates/help-template/HelpTemplate.tsx
  src/components/templates/help-template/styled.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/types/help.d.ts
Labels: 🎨 Publish

#136 Publish/board 2/#120
  src/apis/help.ts
  src/apis/mentor.ts
  src/apis/user.ts
  src/components/common/badge-list/badgeList.json
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/molecules/mentor-board-elements/MentorOtherBoardCard.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBody.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBottom.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHead.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/mentor-board/styled.ts
  src/components/organisms/modify-help-board/ModifyHelpBoard.tsx
  src/components/templates/ModifyHelpTemplate.tsx
  src/pages/modify/index.tsx
  src/types/help.d.ts
  src/types/mentor.d.ts
Labels: 🎨 Publish

#137 멘토게시글 수정
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHead.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/types/mentor.d.ts
Labels: 📝 Modify

#141 멘토 리뷰, 유닛, 게시글
  src/apis/mentor.ts
  src/apis/mentors.ts
  src/components/common/badge-list/badge.ts
  src/components/common/badge-list/badgeList.json
  src/components/molecules/mentor-elements/MentorBadgeElements.tsx
  src/components/molecules/mentor-elements/MentorCard.tsx
  src/components/molecules/mentor-elements/PopularMentorCard.tsx
  src/components/molecules/mentor-elements/styled.tsx
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/molecules/mentor-review-elements/styled.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/MentorUnitOtherBoard.tsx
  src/components/organisms/mentor/styled.ts
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/recoil/atoms/SideViewerAtom.ts
  src/types/mentor.d.ts
  src/types/user.d.ts
Labels: ✨ Feature, 🎨 Publish, 📝 Modify

#142 멘토 수정
  src/components/molecules/mentor-board-elements/MentorBoardCard.tsx
  src/components/molecules/mentor-elements/MentorCard.tsx
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/molecules/mentor-review-elements/styled.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/organisms/mentor/PopularMentor.tsx
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/components/templates/userpage-template/UserpageTemplate.tsx
  src/components/templates/userpage-template/styled.ts
Labels: 📝 Modify

#143 feat(#138):고객지원 페이지 생성
  src/components/common/globalStyled/styled.ts
  src/components/templates/SupportTemplate.tsx
  src/components/templates/support-template/SupportTemplate.tsx
  src/components/templates/support-template/styled.tsx
  src/pages/support/QnA/index.tsx
  src/pages/support/index.tsx
Labels: ✨ Feature, 🎨 Publish

#144 고객지원 페이지 구현
  src/components/common/globalStyled/styled.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/organisms/support-combo-box/SupportComboBox.tsx
  src/components/organisms/support-combo-box/styled.ts
  src/components/organisms/support-withdrawal/UserWithdrawal.tsx
  src/components/organisms/support-withdrawal/styled.ts
  src/components/templates/SettingTemplate.tsx
  src/components/templates/support-template/PrivacyPolicyTmeplate.tsx
  src/components/templates/support-template/QnATemplate.tsx
  src/components/templates/support-template/SupportTemplate.tsx
  src/components/templates/support-template/TermsConditionsTemplate.tsx
  src/components/templates/support-template/WithdrawalTemplate.tsx
  src/components/templates/support-template/styled.tsx
  src/pages/setting/index.tsx
  src/pages/support/QnA/index.tsx
  src/pages/support/privacy-policy/index.tsx
  src/pages/support/terms-conditions/index.tsx
  src/pages/support/withdrawal/index.tsx
  src/types/support.d.ts
Labels: ✨ Feature, 🎨 Publish, 📝 Modify

#147 리스트 유닛 타입 변경 및 예외처리
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/types/review.d.ts
Labels: 📝 Modify

#148 마이페이지 기능구현 및 퍼블리싱
  src/apis/user.ts
  src/components/common/badge-list/badge.ts
  src/components/common/check-list/checkList.ts
  src/components/common/globalStyled/styled.ts
  src/components/common/rank/rankList.ts
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/molecules/mentor-review-elements/MentorReviewElements.tsx
  src/components/molecules/mentor-review-elements/styled.tsx
  src/components/molecules/my-page-elements/MyBadge.tsx
  src/components/molecules/my-page-elements/MyRank.tsx
  src/components/molecules/my-page-elements/styled.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/my-badge/MyBadge.tsx
  src/components/organisms/my-badge/MyBadgeContents.tsx
  src/components/organisms/my-badge/MyRank.tsx
  src/components/organisms/my-badge/styled.tsx
  src/components/organisms/my-profile/MyProfileConetents.tsx
  src/components/organisms/my-profile/UpdateMyProfile.tsx
  src/components/organisms/my-profile/styled.tsx
  src/components/organisms/my-record/MyRecordContents.tsx
  src/components/organisms/my-record/styled.tsx
  src/components/organisms/my-review/MyReviewContents.tsx
  src/components/organisms/my-review/styled.tsx
  src/components/templates/mypage-template/BadgeTemplate.tsx
  src/components/templates/mypage-template/MyProfileTemplate.tsx
  src/components/templates/mypage-template/MyRecordTemplate.tsx
  src/components/templates/mypage-template/MyReviewTemplate.tsx
  src/components/templates/mypage-template/UpdateMyProfileTemplate.tsx
  src/components/templates/mypage-template/styled.ts
  src/types/help.d.ts
  src/types/mypage.d.ts
  src/types/review.d.ts
  src/types/user.d.ts
Labels: ✨ Feature, 🎨 Publish

#149 고객지원 페이지 구성
  src/apis/oauth.ts
  src/components/organisms/support-combo-box/SupportComboBox.tsx
  src/components/organisms/support-combo-box/styled.ts
  src/components/templates/support-template/QnATemplate.tsx
  src/components/templates/support-template/SupportTemplate.tsx
  src/components/templates/support-template/styled.tsx
Labels: ✨ Feature

#151 Feat/chatting 2/#114
  package-lock.json
  package.json
  src/apis/chat.ts
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomListBox.tsx
  src/components/molecules/chat-list-area/chat-list-box/ChatRoomOutModal.tsx
  src/components/molecules/chat-list-area/mentor-list-box/MentorListBox.tsx
  src/components/organisms/chat/chat-list/ChatRoomList.tsx
  src/components/organisms/chat/chat-space/ChatSpace.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/templates/ChatPageTemplate.tsx
  src/hooks/useCreateRoom.tsx
  src/hooks/useSocket.tsx
  src/pages/_app.tsx
  src/recoil/atoms/ChatPartnersAtom.ts
  src/recoil/atoms/MentorInfoAtom.ts
  src/types/mentor.d.ts
Labels: ✨ Feature

#154 Modify/list 1/#150
  src/apis/count.ts
  src/apis/helpComment.ts
  src/apis/mentor.ts
  src/components/common/category/Category.tsx
  src/components/common/globalStyled/styled.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-board/HelpPullingBoardList.tsx
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor-board/RandomMentorBoard.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/mentor/PopularMentor.tsx
  src/components/organisms/mentor/RankMentor.tsx
  src/components/templates/help-template/HelpTemplate.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/pages/help/index.tsx
  src/pages/mentor/board/index.tsx
  src/pages/mentor/index.tsx
  src/recoil/atoms/CategorySelectAtom.ts
Labels: 📝 Modify

#160 로그인 모달 UI변경
  src/components/molecules/auth-elements/AuthProvider.tsx
  src/components/organisms/auth/LoginModal.tsx
Labels: 🎨 Publish

#161 Publish/main page re publish 1/#112 - mainPagePublsih 1차 완성
  package-lock.json
  package.json
  src/components/common/footer/Footer.tsx
  src/components/common/footer/styled.ts
  src/components/common/footer/styled.tsx
  src/components/molecules/mainpagebody-contents/BodyContents1.tsx
  src/components/molecules/mainpagebody-contents/BodyContents2.tsx
  src/components/molecules/mainpagebody-contents/BodyContents3.tsx
  src/components/molecules/mainpagebody-contents/BodyContents4.tsx
  src/components/molecules/mainpagebody-contents/BodyContents5.tsx
  src/components/molecules/mainpagebody-contents/styled.tsx
  src/components/organisms/mainpage-body/MainPageBody.tsx
  src/components/organisms/mainpage-body/marquee/CategoryMarquee.tsx
  src/components/organisms/mainpage-body/marquee/styled.tsx
  src/components/organisms/mainpage-body/styled.tsx
  src/styles/globals.css
Labels: 🎨 Publish

#163 멘토 유닛 수정
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBody.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBottom.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/mentor-board/styled.ts
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/styled.ts
  src/components/templates/mentor-template/MentorUnitTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/pages/mentor/board/index.tsx
Labels: 📝 Modify

#164 skeletonUI구현
  src/components/common/skeletonUI/SkeletonUI.tsx
  src/components/organisms/help-board/HelpBoardCardList.tsx
  src/components/organisms/help-board/HelpPullingBoardList.tsx
  src/components/organisms/mentor-board/MentorBoardList.tsx
  src/components/organisms/mentor-board/PopularMentorBoardList.tsx
  src/components/organisms/mentor-board/RandomMentorBoard.tsx
  src/components/organisms/mentor/MentorList.tsx
  src/components/organisms/mentor/PopularMentor.tsx
  src/components/organisms/mentor/RankMentor.tsx
  src/components/templates/help-template/HelpTemplate.tsx
  src/components/templates/mentor-template/MentorBoardTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
Labels: ✨ Feature

#167 modify(#157):토큰 에러 핸들링
  src/apis/axiosInstance.ts
  src/components/common/header/MainPageHeader.tsx
  src/components/organisms/auth/AfterLoginModal.tsx
  src/components/organisms/auth/SaveToken.tsx
  src/components/organisms/support-withdrawal/UserWithdrawal.tsx
  src/recoil/atoms/CategorySelectAtom.ts
  src/recoil/atoms/LoginStateAtom.ts
Labels: 📝 Modify

#169 스켈레톤UI추가 및 비율작업
  src/apis/mentor.ts
  src/components/molecules/help-unit-elements/HelpUnitContentBodySkeleton.tsx
  src/components/molecules/help-unit-elements/HelpUnitContentHeadSkeleton.tsx
  src/components/molecules/help-unit-elements/UnitComment.tsx
  src/components/molecules/help-unit-elements/UnitConentHead.tsx
  src/components/molecules/help-unit-elements/UnitContentBody.tsx
  src/components/molecules/help-unit-elements/styled.ts
  src/components/molecules/mentor-board-elements/MentorOtherBoardCard.tsx
  src/components/molecules/mentor-board-elements/styled.ts
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBodySkeleton.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitBottom.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHeadSkeleton.tsx
  src/components/molecules/mentor-board-unit-elements/style.ts
  src/components/organisms/help-unit/HelpUnitContent.tsx
  src/components/organisms/help-unit/styled.ts
  src/components/organisms/mentor-board/MentorBoardUnit.tsx
  src/components/organisms/mentor/MentorReview.tsx
  src/components/organisms/mentor/MentorUnit.tsx
  src/components/organisms/mentor/styled.ts
  src/components/templates/help-template/HelpUnitTemplate.tsx
  src/components/templates/mentor-template/styled.ts
  src/hooks/useSocket.tsx
Labels: ✨ Feature, 📝 Modify

#171 고객지원 페이지 구현
  src/components/common/footer/Footer.tsx
  src/components/common/footer/styled.tsx
  src/components/organisms/terms-conditions/PrivacyPolicyContent.tsx
  src/components/organisms/terms-conditions/TermsConditionsContent.tsx
  src/components/organisms/terms-conditions/styled.tsx
  src/components/templates/MainPageTemplate.tsx
  src/components/templates/mentor-template/MentorTemplate.tsx
  src/components/templates/support-template/PrivacyPolicyTmeplate.tsx
  src/components/templates/support-template/QnATemplate.tsx
  src/components/templates/support-template/SupportTemplate.tsx
  src/components/templates/support-template/TermsConditionsTemplate.tsx
Labels: 📃 Docs

#168 Deploy/https front/#152
  docker-compose.yml
  dockerfile
  entrypoint.sh
  nginx.conf
Labels: 🌏 Deploy

#173 게시글 생성,수정 기능 수정
  src/apis/mentor.ts
  src/components/molecules/create-board-elements/CategorySelector.tsx
  src/components/molecules/create-board-elements/ChoiceSection.tsx
  src/components/molecules/mentor-board-unit-elements/MentorBoardUnitHead.tsx
  src/components/organisms/create-board/CreateBody.tsx
  src/components/organisms/create-board/styled.ts
  src/components/organisms/modify-help-board/ModifyHelpBoard.tsx
  src/components/organisms/modify-help-board/styled.ts
  src/components/templates/CreateTemplate.tsx
  src/components/templates/ModifyHelpTemplate.tsx
  src/styles/globals.css
Labels: 📝 Modify

#175 마이페이지 기능 수정
  src/components/molecules/my-page-elements/MyRank.tsx
  src/components/organisms/my-profile/MyProfileConetents.tsx
  src/components/organisms/my-profile/styled.tsx
  src/components/organisms/my-record/styled.tsx
  src/components/organisms/my-review/MyReviewContents.tsx
  src/components/templates/mypage-template/styled.ts
  src/types/user.d.ts
Labels: 📝 Modify

#176 deploy(#152) CI/CD 최적화
  .github/workflows/ma6-menbosha.yml
Labels: ⚙ Setting, 🌏 Deploy

#177 Deploy/https front/#152
  .github/workflows/ma6-menbosha.yml
Labels: ⚙ Setting

#178 deploy(#152)ec2 내의 .env를 action이 동작할때 불러오기
  .github/workflows/ma6-menbosha.yml
Labels: 🌏 Deploy

#180 deploy(#152) docker-compose를 통한 restart
  .github/workflows/ma6-menbosha.yml
Labels: 🌏 Deploy
